accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import LogoutView

from .views import CreateUserView, LoginUserView

urlpatterns = [
    url(r'^register/$', CreateUserView.as_view(), name='register'),
    url(r'^login/$', LoginUserView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=settings.LOGIN_URL), name='logout'),
]

logger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^logs/', include('logs.urls', namespace='logs')),
    url(r'^api/logs/', include('logs.api.urls', namespace='api-logs')),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^$', RedirectView.as_view(pattern_name='logs:list')),
]

logs/api/urls.py
from django.conf.urls import url

from .views import CreateLogView

urlpatterns = [
    url(r'^create/$', CreateLogView.as_view(), name='create'),
]

logs/urls.py
from django.conf.urls import url

from .views import ListLogsView

urlpatterns = [
    url(r'^$', ListLogsView.as_view(), name='list'),
]

accounts/models.py
from django.db import models

# Create your models here.

logs/models.py
from django.conf import settings
from django.db import models

# Create your models here.
LOG_TYPES = (
    ('info', 'Info'),
    ('warning', 'Warning'),
    ('error', 'Error')
)


class LogManager(models.Manager):

    def get_user_logs(self, user):
        return self.get_queryset().filter(user=user)

    def get_server_logs(self, user, server_name):
        return self.get_user_logs(user).filter(server_name=server_name)


class Log(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=LOG_TYPES)
    message = models.CharField(max_length=200)
    text = models.TextField(blank=True, null=True)
    server_name = models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = LogManager()

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return str(self.message)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()


class CreateUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username:
            username = username.lower()
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError('username already exist')
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        print(self.cleaned_data)
        if password1 and password2 and password1 == password2:
            return password2
        raise forms.ValidationError("passwords doesn't match")

    def save(self, commit=True):
        user_obj = super().save(commit=False)
        password1 = self.cleaned_data.get('password1')
        user_obj.set_password(password1)
        if commit:
            user_obj.save()
        return user_obj


class LoginUserForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError('wrong username or password')
        self.user = user
        return self.cleaned_data

accounts/views.py
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView

from .forms import CreateUserForm, LoginUserForm
from .mixins import LoggedUserRedirectMixin


class CreateUserView(LoggedUserRedirectMixin, CreateView):
    template_name = 'accounts/login-register.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('accounts:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Register'
        return context


class LoginUserView(LoggedUserRedirectMixin, FormView):
    form_class = LoginUserForm
    success_url = reverse_lazy('logs:list')
    template_name = 'accounts/login-register.html'

    def form_valid(self, form):
        if form.is_valid():
            login(self.request, form.user)
            return super().form_valid(form)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Login'
        return context

logs/api/views.py
from rest_framework.generics import CreateAPIView

from logs.models import Log

from .serializers import CreateLogSerializer


class CreateLogView(CreateAPIView):
    queryset = Log.objects.all()
    serializer_class = CreateLogSerializer

logs/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from .models import Log


@method_decorator(login_required, name='dispatch')
class ListLogsView(ListView):
    template_name = 'logs/list.html'
    paginate_by = 10

    def get_queryset(self):
        server_name = self.request.GET.get('q', None)
        if server_name:
            return Log.objects.get_server_logs(user=self.request.user, server_name=server_name)
        return Log.objects.get_user_logs(user=self.request.user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['server_name'] = self.request.GET.get('q', None)
        # presist query paramas when paginating
        get_copy = self.request.GET.copy()
        query_params = get_copy.pop('page', True) and get_copy.urlencode()
        context_data['query_params'] = query_params

        return context_data

accounts/templates/accounts/login-register.html
{% extends 'base.html' %}
{%block content%}

    <h1>{{title}}</h1>


    {% include 'accounts/snippets/post-form.html' %}


{% endblock %}

accounts/templates/accounts/snippets/post-form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

logs/templates/logs/list.html
{% extends 'base.html' %}

{% block content %}


    {% if object_list.exists %}
        {% if server_name %}
            <h1>"{{server_name}}" Server Logs</h1>
        {%else%}
            <h1>All Logs</h1>
        {%endif%}

        <table>
            <tr>
                <th>Server Name</th>
                <th>Type</th>
                <th>Message</th>
                <th>Text</th>
                <th>Timestamp</th>
            </tr>
            {% for log in object_list %}
                <tr>
                    <td>
                        {%if log.server_name %}
                            {{ log.server_name }}
                        {%endif%}
                    </td>
                    <td>{{ log.type }}</td>
                    <td>{{ log.message }}</td>
                    <td class="log-text">
                        {%if log.text%}
                            {{ log.text }}
                        {%endif%}
                    </td>
                    <td>
                        {{ log.timestamp|date:"D d M Y" }} {{ log.timestamp|time:"H:i" }}
                    </td>
                </tr>
            {% endfor %}

        </table>

       
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1&{{query_params}}">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}&{{query_params}}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&{{query_params}}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}&{{query_params}}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
       
    {%else%}
       
        {% if server_name %}
            <h1>"{{server_name}}" server deosn't exist</h1>
        {%else%}
            <h1>No Logs yet</h1>
        {%endif%}
    {% endif %}

   
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <style>
        .navbar {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }
        
        .navbar li {
            float: left;
        }

        .navbar li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        .navbar li span {
            display: block;
            color: burlywood;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .navbar li .home {
            color: burlywood !important;      
        }

        .navbar li a:hover:not(.active) {
            background-color: #111;
        }

        .navbar .active {
            background-color: #4CAF50;
        }
        .navbar li form {
            display: block;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        .log-text{
            word-break: break-word;
        }
        table, th, td {
            border: 1px solid black;
        }
        table {
            border-collapse: collapse;
        }
    </style>
</head>

<body>

    <ul class="navbar">
        {% if not request.user.is_authenticated %}
            <li><span>Logs aggregator</span></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:register' %}">Register</a></li>
        {%else%}
            <li><a class="home" href="{% url 'logs:list' %}">Logs aggregator</a></li>
            <li>
                {% include 'snippets/search-form.html' %}
            </li>
            <li style="float:right"><a class="active" href="{% url 'accounts:logout' %}">Logout</a></li>
            <li style="float:right"><span>{{request.user.username}}</span></li>
        {%endif%}
    </ul>

    {% block content %}{% endblock %}

</body>

</html>

templates/snippets/search-form.html
<form>
    <input type="search" name="q" placeholder="search by server name">
    <input type="submit">
</form>